<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-06 01:59
=======
# Generated by Django 5.0.4 on 2025-05-12 02:10
>>>>>>> main

import django.db.models.deletion
import django.utils.timezone
import uniescolar.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
<<<<<<< HEAD
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=30)),
=======
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=30, null=True)),
>>>>>>> main
                ('data_nascimento', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('nome', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('materia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('senha', models.CharField(default='default_password', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('numero', models.IntegerField()),
                ('local', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(default=uniescolar.models.hora_inicio_padrao)),
                ('hora_fim', models.TimeField(default=uniescolar.models.hora_fim_padrao)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='uniescolar.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina', to='uniescolar.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='uniescolar.professor')),
=======
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(default=uniescolar.models.hora_inicio_padrao)),
                ('hora_fim', models.TimeField(default=uniescolar.models.hora_fim_padrao)),
                ('descricao', models.CharField(max_length=200)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='uniescolar.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina', to='uniescolar.disciplina')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='uniescolar.professor')),
>>>>>>> main
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('CPF', models.CharField(default='', max_length=14, primary_key=True, serialize=False)),
                ('profissao', models.CharField(max_length=255)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PacoteHora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horas_contratadas', models.IntegerField()),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=8)),
<<<<<<< HEAD
                ('saldo', models.IntegerField()),
=======
                ('data_contrato', models.DateField(default=django.utils.timezone.now)),
>>>>>>> main
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes_hora', to='uniescolar.responsavel')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
<<<<<<< HEAD
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='uniescolar.responsavel'),
=======
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='uniescolar.responsavel'),
>>>>>>> main
        ),
    ]
