# Generated by Django 5.2 on 2025-04-21 14:16

import django.db.models.deletion
import django.utils.timezone
import uniescolar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('data_nascimento', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('cpf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='uniescolar.usuario')),
                ('materia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('cpf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='uniescolar.usuario')),
                ('profissao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('local', models.CharField(max_length=100)),
                ('disciplina', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(default=uniescolar.models.hora_inicio_padrao)),
                ('hora_fim', models.TimeField(default=uniescolar.models.hora_fim_padrao)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='uniescolar.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='uniescolar.professor')),
            ],
        ),
        migrations.CreateModel(
            name='PacoteHora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horas_contratadas', models.IntegerField()),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('saldo', models.IntegerField()),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes_hora', to='uniescolar.responsavel')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='uniescolar.responsavel'),
        ),
    ]
