# Generated by Django 5.2 on 2025-05-06 02:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniescolar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacotehora',
            name='saldo',
        ),
        migrations.AddField(
            model_name='pacotehora',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
