# Generated by Django 5.2 on 2025-04-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniescolar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='default_password', max_length=255),
        ),
    ]
