# Generated by Django 5.2 on 2025-05-06 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniescolar', '0002_remove_pacotehora_saldo_pacotehora_data_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacotehora',
            old_name='data_inicio',
            new_name='data_contrato',
        ),
    ]
