# Generated by Django 5.2 on 2025-04-22 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniescolar', '0002_usuario_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='uniescolar.usuario'),
        ),
    ]
