# Generated by Django 5.2 on 2025-04-16 22:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniescolar', '0002_professor_aula_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('profissao', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='aula',
            name='disciplina',
            field=models.CharField(max_length=100),
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='data',
            new_name='data_inicio',
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='termino',
            new_name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(default='Masculino', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2025, 4, 16, 8, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='local',
            field=models.CharField(default='Casa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='cpf',
            field=models.CharField(default=0, max_length=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(default='teste.professor@hotmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='materia',
            field=models.CharField(default='Matematica', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone',
            field=models.CharField(default=11999999999, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aula',
            name='aluno',
            field=models.ForeignKey(default='teste', on_delete=django.db.models.deletion.CASCADE, to='uniescolar.aluno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aula',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(default='professor teste', on_delete=django.db.models.deletion.CASCADE, to='uniescolar.professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='PacoteHora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horas_contratadas', models.IntegerField()),
                ('valor_hora', models.IntegerField()),
                ('saldo', models.IntegerField()),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniescolar.responsavel')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(default='Responsável padrão', on_delete=django.db.models.deletion.CASCADE, to='uniescolar.responsavel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
