# Generated by Django 5.2 on 2025-05-06 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniescolar', '0003_rename_data_inicio_pacotehora_data_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='descricao',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='uniescolar.professor'),
        ),
    ]
