# Generated by Django 5.2 on 2025-05-06 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniescolar', '0004_aula_descricao_alter_aula_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='numero',
        ),
    ]
