# Generated by Django 5.2 on 2025-04-16 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniescolar', '0004_alter_aluno_data_nascimento_alter_aula_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='uniescolar.responsavel'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='uniescolar.aluno'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='uniescolar.professor'),
        ),
        migrations.AlterField(
            model_name='pacotehora',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes_hora', to='uniescolar.responsavel'),
        ),
    ]
