# Generated by Django 5.2 on 2025-04-22 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniescolar', '0004_alter_responsavel_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='cpf',
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='CPF',
            field=models.CharField(default='', max_length=11, primary_key=True, serialize=False),
        ),
    ]
