# Generated by Django 5.2 on 2025-04-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniescolar', '0005_remove_responsavel_cpf_alter_responsavel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
