# Generated by Django 5.2 on 2025-04-21 18:34

import django.db.models.deletion
import django.utils.timezone
import uniescolar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniescolar', '0005_alter_aluno_responsavel_alter_aula_aluno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='aula',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aula',
            name='hora_fim',
            field=models.TimeField(default=uniescolar.models.hora_fim_padrao),
        ),
        migrations.AlterField(
            model_name='aula',
            name='hora_inicio',
            field=models.TimeField(default=uniescolar.models.hora_inicio_padrao),
        ),
        migrations.AlterField(
            model_name='pacotehora',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='profissao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='uniescolar.usuario'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='cpf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='uniescolar.usuario'),
        ),
    ]
