# Generated by Django 5.2 on 2025-04-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniescolar', '0006_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='CPF',
            field=models.CharField(default='', max_length=14, primary_key=True, serialize=False),
        ),
    ]
